version: "3.9"
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./keyspace.cql:/keyspace.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /keyspace.cql"
  migrate:
    build: .
    # image: liquibase/liquibase
    container_name: migrate
    volumes: 
      - ./wait-for.sh:/liquibase/wait-for.sh
      - ./changelog.sql:/liquibase/changelog/changelog.sql
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./lib:/liquibase/classpath 
    entrypoint:
      - "./wait-for.sh"
      - "cassandra:9042"
      - "-t 200"
      - "--"
      - "sh"
      - "-c"
      - "liquibase update"
    depends_on:
      - cassandra
