#!/bin/bash

docker run \
    --rm \
    -v $(pwd)/changelog.sql:/liquibase/changelog/changelog.sql \
    -v $(pwd)/liquibase.properties:/liquibase/liquibase.properties \
    -v $(pwd)/lib:/liquibase/classpath \
    --network=liquibase-cassandra_default \
    liquibase/liquibase \
    liquibase history